# @format

# Ollama
# Install and configure the Ollama LLM runner service.
---
- name: Ensure ollama user is present
  become: true
  block:
    - name: Ensure ollama group is present
      ansible.builtin.group:
        name: "{{ ollama_user_name }}"
        gid: "{{ ollama_user_id }}"
        system: true
        state: present

    - name: Ensure ollama user is present
      ansible.builtin.user:
        name: "{{ ollama_user_name }}"
        group: "{{ ollama_user_name }}"
        password: "*"
        shell: "{{ ollama_user_shell }}"
        create_home: false
        uid: "{{ ollama_user_id }}"
        state: present

- name: Setup GPU hardware acceleration
  become: true
  block:
    - name: Install kernel headers to build NVIDIA drivers
      ansible.builtin.apt:
        name: linux-headers-amd64
        update_cache: true
        state: present

    - name: Install NVIDIA drivers & firmware
      ansible.builtin.apt:
        name:
          - nvidia-driver
          - firmware-misc-nonfree
          - libnvcuvid1
          - libnvidia-encode1
        update_cache: true
        state: present
      notify: Reboot system
      ignore_errors: true

    - name: Add nvidia container repository key
      ansible.builtin.get_url:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        dest: /etc/apt/trusted.gpg.d/nvidia-container-toolkit.asc
        owner: root
        group: root
        mode: "0644"

    - name: Add nvidia container toolkit repository
      ansible.builtin.copy:
        src: files/nvidia-container-toolkit.sources
        dest: /etc/apt/sources.list.d/nvidia-container-toolkit.sources
        owner: root
        group: root
        mode: "0644"

    - name: Ensure NVIDIA container toolkit is installed
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        update_cache: true
        state: present

    - name: Configure Docker with NVIDIA container toolkit
      ansible.builtin.command:
        cmd: nvidia-ctk runtime configure --runtime=docker
      changed_when: true

    - name: Restart Docker daemon
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: restarted

    - name: Add git exception for nvidia patcher directory
      community.general.git_config:
        name: safe.directory
        value: /opt/nvidia-patch
        scope: global
        state: present

    - name: Clone NVENC encoding restriction patcher
      ansible.builtin.git:
        repo: https://github.com/keylase/nvidia-patch.git
        dest: /opt/nvidia-patch # noqa: latest
        force: true

    - name: Ensure owner of nvidia patcher application directory is set
      ansible.builtin.file:
        path: /opt/nvidia-patch
        owner: "{{ ollama_user_name }}"
        group: "{{ ollama_user_name }}"
        mode: "0740"
        recurse: true
        follow: false
        state: directory

    - name: Check if nvidia drivers is running
      ansible.builtin.command:
        cmd: nvidia-smi
      register: driver_output
      changed_when: false
      ignore_errors: true

    - name: Reboot system
      ansible.builtin.reboot:
      when: driver_output.rc == 9

    - name: Patch NVENC driver
      ansible.builtin.command:
        chdir: /opt/nvidia-patch
        cmd: ./patch.sh
      register: patch_output
      changed_when: "'Patched!' in patch_output.stdout_lines"

- name: Setup ollama application files
  become: true
  block:
    - name: Ensure ollama directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ ollama_user_name }}"
        group: "{{ ollama_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ ollama_user_name }}"
        group: "{{ ollama_user_name }}"
        mode: "0640"

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
      - "{{ ollama_hostname }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Get latest versions from github
  ansible.builtin.include_tasks: get-versions.yaml
  vars:
    versions_list:
      - latest
  loop:
    - name: ollama
      docker_user: ollama
      docker_repo: ollama
    - name: open_webui
      docker_user: open-webui
      docker_repo: open-webui

- name: Start ollama docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present

- name: Set version files
  become: true
  ansible.builtin.template:
    src: templates/app.{{ item }}.VERSION
    dest: "{{ docker_project_src }}/{{ item }}.VERSION"
    owner: "{{ ollama_user_name }}"
    group: "{{ ollama_user_name }}"
    mode: "0640"
  loop:
    - ollama
    - open-webui
