# @format
---
## NFSv4-client-setup variables
# Kerberos
nfs_krb5_realm: TINYNAMOO.COM
nfs_krb5_kdc: storage.tinynamoo.com
nfs_krb5_admin_server: storage.tinynamoo.com

# NFS
nfs_mount_server: storage.tinynamoo.com
nfs_idmapd_domain: tinynamoo.com

# NFS client variables
nfs_clients:
  bazarr:
    name: bazarr
    uid: 118
    groups: media
  drop:
    name: drop
    uid: 231
  firefly:
    name: firefly
    uid: 160
  gitea:
    name: gitea
    uid: 180
  immich:
    name: immich
    uid: 120
  jellyfin:
    name: jellyfin
    uid: 281
    groups: media
  nextcloud:
    name: nextcloud
    uid: 233
  paperless:
    name: paperless
    uid: 130
  prowlarr:
    name: prowlarr
    uid: 286
    groups: media
  qbittorrent:
    name: qbit
    uid: 284
    groups: media
  radarr:
    name: radarr
    uid: 283
    groups: media
  send:
    name: send
    uid: 210
  sonarr:
    name: sonarr
    uid: 282
    groups: media
  vikunja:
    name: vikunja
    uid: 240
  wikijs:
    name: wikijs
    uid: 170

nfs_groups:
  media:
    name: media
    gid: 200
