# @format

# Stirling PDF
# Install and configure Stirling PDF tools collection.
---
- name: Ensure stirling-pdf user is present
  become: true
  block:
    - name: Ensure stirling-pdf group is present
      ansible.builtin.group:
        name: "{{ stirling_pdf_user_name }}"
        gid: "{{ stirling_pdf_user_id }}"
        system: true
        state: present

    - name: Ensure stirling-pdf user is present
      ansible.builtin.user:
        name: "{{ stirling_pdf_user_name }}"
        group: "{{ stirling_pdf_user_name }}"
        password: "*"
        shell: "{{ stirling_pdf_user_shell }}"
        create_home: false
        uid: "{{ stirling_pdf_user_id }}"
        state: present

- name: Create application directory
  become: true
  ansible.builtin.file:
    path: "{{ docker_project_src }}"
    owner: "{{ stirling_pdf_user_name }}"
    group: "{{ stirling_pdf_user_name }}"
    mode: "0640"
    state: directory

- name: Setup Stirling PDF docker compose file
  become: true
  ansible.builtin.template:
    src: templates/app.docker-compose.yaml
    dest: "{{ docker_project_src }}/docker-compose.yaml"
    owner: "{{ stirling_pdf_user_name }}"
    group: "{{ stirling_pdf_user_name }}"
    mode: "0640"

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start Stirling PDF docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
