# @format

# Prometheus
# Install and configure Prometheus metrics aggregation server.
---
- name: Ensure prometheus user is present
  become: true
  block:
    - name: Ensure prometheus group is present
      ansible.builtin.group:
        name: "{{ prometheus_user_name }}"
        gid: "{{ prometheus_user_id }}"
        system: true
        state: present

    - name: Ensure prometheus user is present
      ansible.builtin.user:
        name: "{{ prometheus_user_name }}"
        group: "{{ prometheus_user_name }}"
        password: "*"
        shell: "{{ prometheus_user_shell }}"
        create_home: false
        uid: "{{ prometheus_user_id }}"
        state: present

- name: Setup Prometheus application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ prometheus_user_name }}"
        group: "{{ prometheus_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ prometheus_user_name }}"
        group: "{{ prometheus_user_name }}"
        mode: "0640"

    - name: Setup prometheus configuration file
      ansible.builtin.template:
        src: templates/app.config.yml
        dest: '{{ debian_additional_disks["appdata"]["mount_point"] }}/prometheus/prometheus.yml'
        owner: "{{ prometheus_user_name }}"
        group: "{{ prometheus_user_name }}"
        mode: "0640"
      register: prometheus_config_file

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Get latest prometheus container release from github
  become: false
  community.general.github_release:
    user: prometheus
    repo: prometheus
    action: latest_release
  delegate_to: localhost
  register: prometheus_github_release

- name: Extract latest prometheus container version
  ansible.builtin.set_fact:
    prometheus_latest_version: "{{ prometheus_github_release.tag }}"

- name: Start prometheus docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
  register: docker_containers_started

- name: Restart prometheus docker containers (if config file changed)
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: restarted
  when: prometheus_config_file.changed and not docker_containers_started.changed

- name: Set version file
  become: true
  ansible.builtin.template:
    src: templates/app.VERSION
    dest: "{{ docker_project_src }}/VERSION"
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_user_name }}"
    mode: "0640"
  when: docker_containers_started.changed
