# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.10.1

# User
debian_user_name: melanie
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILmxlXueWqzE8G+MicNIbZOlznlKBNHd268MYlyNl98H melanie@metrics.tinynamoo.com"

prometheus_user_name: prometheus
prometheus_user_id: 191
prometheus_user_shell: /usr/sbin/nologin

## NGINX variables
nginx_conf_files:
  - filename: prometheus.conf
    path: templates/nginx.prometheus.conf

## Proxmox instance variables
proxmox_snapshot_vmid: 10191
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: prometheus
docker_project_src: /opt/prometheus
