# @format

# Your-Spotify
# Install and configure the Your-Spotify statistics server.
---
- name: Ensure your-spotify user is present
  become: true
  block:
    - name: Ensure your-spotify group is present
      ansible.builtin.group:
        name: "{{ your_spotify_user_name }}"
        gid: "{{ your_spotify_user_id }}"
        system: true
        state: present

    - name: Ensure your-spotify user is present
      ansible.builtin.user:
        name: "{{ your_spotify_user_name }}"
        group: "{{ your_spotify_user_name }}"
        password: "*"
        shell: "{{ your_spotify_user_shell }}"
        create_home: false
        uid: "{{ your_spotify_user_id }}"
        state: present

- name: Setup your-spotify application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ your_spotify_user_name }}"
        group: "{{ your_spotify_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ your_spotify_user_name }}"
        group: "{{ your_spotify_user_name }}"
        mode: "0640"

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
      - "{{ your_spotify_api_hostname }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start your-spotify docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
