# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.20.1

# User
debian_user_name: juliette
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAIVlf7iMs/iJm/+rAS3uH5jBaIdjbztb0+17AL2ZwHh juliette@media.tinynamoo.com"

seerr_user_name: seerr
seerr_user_id: 285
seerr_user_shell: /usr/sbin/nologin

## NGINX variables
nginx_conf_files:
  - filename: seerr.conf
    path: templates/nginx.seerr.conf

## Seerr variables
seerr_docker_name: seerr

## Proxmox variables
proxmox_snapshot_vmid: 20116
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: seerr
docker_project_src: /opt/seerr
