# @format
---
## Debian-12-setup-variables
debian_user_password: $6$75fbHNgVYiz.6Fcf$EohrK8XwIxuwwkZxw7RAauOnov0bSasTOMO6hRTU9U/OgUMMJdnqWv1C.ZksfgUvxYl/kPGsrJsqY8X0gLyOA0
debian_root_password: $6$edxE3TJbSHZj2qT5$JUWP2Yb/AH2S6Vzcf6CR.bVIQHWksxsZRqW0xkbPImfgO.e9sEUv6IScB1uc/pbb15cQ2agRjQ43JIPhnjAeb/

debian_additional_disks:
  appdata:
    uuid: 9dcee7db-9cce-4664-b873-07b114675dc2
    mount_point: /srv/appdata
  postgres:
    uuid: 89e22bac-6c1a-4401-8cd9-5a113270bd95
    mount_point: /srv/postgres

## Nextcloud variables:
nextcloud_postgres_pass: DSC"5,d,V}\5*gj;Xw^#

nextcloud_collabora_admin_username: admin
nextcloud_collabora_admin_pass: =H.\;m}7>r~"JVz=g5zy

nextcloud_smtp_username: sunny@mail.tinynamoo.com
nextcloud_smtp_proton_token: Q7LV652RT3ELKN62
