$ANSIBLE_VAULT;1.1;AES256
38306265386633653934626337653936616134313161383435616165313231656465366431333738
6232666364323563323164626464303238666534393038330a653062653466663764623535376231
65623839376239623232306535343830346231613563373630656538636264316664663230323964
3534383665323962340a633664643038653630373030366232626130313737656332383133663434
39646663633164313036386335623663623362353333313161613238393030376463393632356165
32343438343131373538346161373462623263363734306632663732303634633966666135323533
63383933393230376430623765613462666238336131633733326231343765383238306237386663
61313566393765343934373735343264333665326633656538643633656133663363613231366635
66313134613362643234303033626662356536626465393432666462336435393236323132323438
37626131336165343165383263323536376462663736326238346561306130613234343832643332
33383434363962626162663264323037346166333231633935623239336664376362353761346432
31363036333532316337323235326463666161396561383562613234643932363334346230356362
65386332323131366638373461353662663562316263663138333466636235313163366231393533
30373533336566373364643839316135393439346139333036393938653965643236366231396466
33643339393932623962616531366331653231376634336262643630353062393631396162336539
37373164653236363734613762353037373762323930393935333838383263396563646466373436
30376464333661646664666438613132363130623330313231363964373632356131386538663463
35656638346663336233633261623761346230323933343463313037623331306233393666643966
62613931383932343132353537663266363361383464376561643265653266646332343335303736
61623134373965313761373036306430663562306434363131373965633064653930663536376139
38343532383166333136383936306232323036333466336166616434393539636464346365363265
65323535653030323631663337346264383934333737636231363363306639386237386335633439
31666138656462336430663334363437353163646632353061336163376265353030663764333064
63636137343239306163363138633264643464646161653661333066643735626662383538323262
65656462313937653735626163613934393133386264626433323733376632663165323231346337
62343135643130633832363230303265393463323235303636636161393838653433373630333334
63396363393166643039313662323234636530396238653235376235646135323161653235636135
61643935343033663439356437616439323135353233373363333039663266316638323464663165
30656235323438653836306565336135383939313563373737353031343732333630393235333764
34643433366233326330353737396665643232663263343631666434313565326231363732646166
363461333166326335653662646361393832
