# @format

# Karakeep
# Upgrade the Karakeep bookmarking service
---
- name: Check if containers requires update
  become: true
  block:
    - name: Get karakeep version file
      ansible.builtin.slurp:
        src: "{{ docker_project_src }}/VERSION"
      register: version_file

    - name: Extract version information
      ansible.builtin.set_fact:
        karakeep_image_version: "{{ version_file['content'] | b64decode | trim }}"

    - name: Get latest karakeep release from github
      become: false
      community.general.github_release:
        user: karakeep-app
        repo: karakeep
        action: latest_release
      delegate_to: localhost
      register: github_release

    - name: Extract latest containers versions
      ansible.builtin.set_fact:
        karakeep_latest_version: "{{ github_release.tag }}" # noqa: var-naming[no-jinja]

    - name: Check if applications have updates
      ansible.builtin.set_fact:
        karakeep_has_updates: "{{ karakeep_image_version != karakeep_latest_version }}"

    - name: Stop play if applications have no updates
      ansible.builtin.meta: end_play
      when: "(not karakeep_has_updates)"

- name: Take snapshot of Proxmox instance
  ansible.builtin.import_role:
    name: proxmox
    public: false
  vars:
    proxmox_task_list: snapshot
    proxmox_snapshot_name: "{{ 'pre_upgrade_' + (karakeep_image_version | regex_replace('[.]', '-')) }}" # noqa: yaml[line-length]
    proxmox_snapshot_description: |
      [Ansible] Working snapshot of karakeep {{ karakeep_image_version }} before upgrading to {{ karakeep_latest_version }}
  delegate_to: localhost

- name: Upgrade karakeep bookmarking service
  become: true
  block:
    - name: Update apt cache, upgrade packages and remove unused dependencies
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        purge: true

    - name: Ensure docker compose file is updated
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ karakeep_user_name }}"
        group: "{{ karakeep_user_name }}"
        mode: "0640"

    - name: Ensure karakeep configuration file is updated
      ansible.builtin.template:
        src: templates/app.configuration.env
        dest: '{{ debian_additional_disks["appdata"]["mount_point"] }}/karakeep/.env'
        owner: "{{ karakeep_user_name }}"
        group: "{{ karakeep_user_name }}"
        mode: "0640"

    - name: Update & start docker containers
      become: true
      community.docker.docker_compose_v2:
        project_name: "{{ docker_project_name }}"
        project_src: "{{ docker_project_src }}"
        remove_orphans: true
        pull: always
        state: present
      register: docker_containers_updated

    - name: Prune unused docker objects
      community.docker.docker_prune:
        builder_cache_all: true
        containers: true
        images: true
        networks: true
        volumes: true

    - name: Update version file
      ansible.builtin.template:
        src: templates/app.VERSION
        dest: "{{ docker_project_src }}/VERSION"
        owner: "{{ karakeep_user_name }}"
        group: "{{ karakeep_user_name }}"
        mode: "0640"
      when: docker_containers_updated.changed
