---
services:
  wallos:
    container_name: {{ wallos_docker_name }}
    image: bellamy/wallos:latest
    environment:
      TZ: "Asia/Singapore"
    volumes:
      - {{ debian_additional_disks["appdata"]["mount_point"] }}/wallos/db:/var/www/html/db
      - {{ debian_additional_disks["appdata"]["mount_point"] }}/wallos/logos:/var/www/html/images/uploads/logos
    ports:
      - 8282:80
    restart: unless-stopped
