services:
  prometheus:
    container_name: {{ docker_project_name }}
    image: prom/prometheus:latest
    volumes:
      - {{ debian_additional_disks["appdata"]["mount_point"] }}/prometheus/data:/prometheus
      - {{ debian_additional_disks["appdata"]["mount_point"] }}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    user: {{ prometheus_user_id }}:{{ prometheus_user_id }}
    restart: unless-stopped
