# @format
---
## debian-13-setup variables
# Datetime
debian_datetime_ntp_server: 172.28.10.1

# User
debian_user_name: sabi
debian_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDFgbN61GZ3bFwke43PBKMNL4ZACZ1Rv/o4K35Jc+C3L sabi@monitor.tinynamoo.com"

grafana_user_name: grafana
grafana_user_id: 192
grafana_user_shell: /usr/sbin/nologin

## NGINX variables
nginx_conf_files:
  - filename: grafana.conf
    path: templates/nginx.grafana.conf

## Grafana variables
grafana_image_version: v12.4.0

## Proxmox instance variables
proxmox_snapshot_vmid: 10192
proxmox_snapshot_retention: 3
proxmox_snapshot_include_ram: false

## Docker variables
docker_project_name: grafana
docker_project_src: /opt/grafana
