$ANSIBLE_VAULT;1.1;AES256
30666662663331336635643066366166323131336564383365653162653336646635376562386236
6465636339353966626162663130343536663837303863350a623734326635353131376430316238
30313465663633666234343039383838653163333234666261353630636161643463336532373035
6238373465616331380a653230383863323561656461643336666231323833646533303435633063
65643136376261386662633564333265626363303763373936653339313731343536633765666236
66396231363266663136313535306365343937363563393433376538323763353064373466383730
30323165303839316135346138373132393339366264663235363363323766376536343264363061
61353335623433366639306566646439366337383066343330653934643965663731343336663165
66653935643138656430376630343135663531366466663865656339323465626635616363363630
63343762653735343831363937613063373364303934653931373738323138323337333235313161
37383239356134303837636337343638373538343135376263326464616337363362333662313836
39303230663139623231316163303632343531366562316536366230366561613462376238333962
63363037663734363232653564323663653538343736323966333333353238393833353030333563
37363763366635663535393939376437313234643036363933393162333133633361393565323566
61613939316139613762376132346164393831303735643064306261656630643936343666616164
34393336373264383037306439653933623139363163623863386231383935396264316433326538
66666230363633633232323232353133613232343730363862356263326639663566383838653162
64376139366263376231393664393034616338313263336336326262636433373963663061376563
32636561626262343539666166643365353264326237306464363066366336353864336166336134
39366438343231623066653964666463626161306563623530303966316564643135323335663165
66653066336433633437326263633466353566653930383539633736316135643631383839346661
35333337343033636661383962623831326663356362626262356534646238323133643139313338
62663239356639643931306339313936356639653630376461303532353464653637396338363264
66653565363963393561366466653365643534306563646466316131346262386332666664623037
65336166333334333736326431316164376334656639663835363635643930326639643034313361
35336431643434363466663532643363366238363866626132356131383663353133626236626263
65663030346637383764336130616433343738363665313262623761613830663563666138386432
37626364303339336233336666346533343132353266643736643435303839346633396336373966
61383135396362303234646336336335646333376234623637373336343334343837306566353938
37346437386362313438313834643033386337656638343564633837333834366532343634633032
62643835373863366131393165333031376531643330346664626264333661383931663332656639
32393135616138653735323262336430336335386662643365343931303931393235363337653263
6663
