# @format

# Grafana
# Install and configure Grafana data visualisation server.
---
- name: Ensure grafana user is present
  become: true
  block:
    - name: Ensure grafana group is present
      ansible.builtin.group:
        name: "{{ grafana_user_name }}"
        gid: "{{ grafana_user_id }}"
        system: true
        state: present

    - name: Ensure grafana user is present
      ansible.builtin.user:
        name: "{{ grafana_user_name }}"
        group: "{{ grafana_user_name }}"
        password: "*"
        shell: "{{ grafana_user_shell }}"
        create_home: false
        uid: "{{ grafana_user_id }}"
        state: present

- name: Setup Grafana application files
  become: true
  block:
    - name: Ensure application directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ grafana_user_name }}"
        group: "{{ grafana_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ grafana_user_name }}"
        group: "{{ grafana_user_name }}"
        mode: "0640"

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Start grafana docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
