# @format

# Miniflux
# Install and configure the Miniflux feed reader server.
---
- name: Ensure miniflux user is present
  become: true
  block:
    - name: Ensure miniflux group is present
      ansible.builtin.group:
        name: "{{ miniflux_user_name }}"
        gid: "{{ miniflux_user_id }}"
        system: true
        state: present

    - name: Ensure miniflux user is present
      ansible.builtin.user:
        name: "{{ miniflux_user_name }}"
        group: "{{ miniflux_user_name }}"
        password: "*"
        shell: "{{ miniflux_user_shell }}"
        create_home: false
        uid: "{{ miniflux_user_id }}"
        state: present

- name: Setup Miniflux application files
  become: true
  block:
    - name: Ensure Miniflux directory is present
      ansible.builtin.file:
        path: "{{ docker_project_src }}"
        owner: "{{ miniflux_user_name }}"
        group: "{{ miniflux_user_name }}"
        mode: "0750"
        state: directory

    - name: Setup docker-compose file
      ansible.builtin.template:
        src: templates/app.docker-compose.yaml
        dest: "{{ docker_project_src }}/docker-compose.yaml"
        owner: "{{ miniflux_user_name }}"
        group: "{{ miniflux_user_name }}"
        mode: "0640"

- name: Install and configure nginx
  vars:
    debian_common_task_list:
      - nginx
    nginx_tls_domains:
      - "{{ ansible_host }}"
  ansible.builtin.include_role:
    name: debian-common

- name: Get latest miniflux container release from github
  become: false
  community.general.github_release:
    user: miniflux
    repo: v2
    action: latest_release
  delegate_to: localhost
  register: miniflux_github_release

- name: Extract latest miniflux container version
  ansible.builtin.set_fact:
    miniflux_latest_version: "{{ miniflux_github_release.tag }}"

- name: Start miniflux docker containers
  become: true
  community.docker.docker_compose_v2:
    project_name: "{{ docker_project_name }}"
    project_src: "{{ docker_project_src }}"
    state: present
  register: docker_containers_started

- name: Set version file
  become: true
  ansible.builtin.template:
    src: templates/app.VERSION
    dest: "{{ docker_project_src }}/VERSION"
    owner: "{{ miniflux_user_name }}"
    group: "{{ miniflux_user_name }}"
    mode: "0640"
  when: docker_containers_started.changed
