$ANSIBLE_VAULT;1.1;AES256
31346237323135306464656338646463666264663762663162616133633861373062323133326262
3333613932626435376232336163306235346332633239370a366462313163363931376230626635
33373534303062353864336362643466623333633362646539616639626132633361363464333564
3138333539643765300a633530636532333764353465623537643936623030326261633235363063
34393038366634323762636333623434626536376532643234623434333534393534356262656565
66316263343730363333386163656664306330666266393735663932623364373362303338316365
30343931366234376364366531393433396165336463373133376631663639336164333533303930
31383964653534396665346437383662353965643232373862393433623366363530346463656433
61303835356538336337393061306165626465633166666236333166623832386434
